"""empty message

Revision ID: 1ec4fee9ebb1
Revises: d027933d45de
Create Date: 2023-06-26 13:47:36.031377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec4fee9ebb1'
down_revision = 'd027933d45de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('orders', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.drop_column('orders')
        batch_op.drop_column('date_created')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('status')
        batch_op.drop_column('invoice')

    # ### end Alembic commands ###
